### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by farberm** [bryanbartow/homebridge-alarm.com#19]
I have update the AP and config file but I get the following error. Any help would be appreciated.

/opt/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Alarmdotcom' was not registered by any plugin.
    at API.accessory (/opt/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/opt/local/lib/node_modules/homebridge/lib/server.js:233:42)
    at Server.run (/opt/local/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/opt/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/opt/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by yungsters** [comment]
In 0.4.0, the plugin was changed to be a platform. You need to move the config from the `accessories` array to the `platforms` array and rename the `accessory` property to `platform`.

**Comment by farberm** [comment]
thx, now working

**Comment by bryanbartow** [comment]
My work is done here ;)
