### ISSUE TITLE
Error Message when running Homebridge 

### ISSUE THREAD

**Issue by jpstephens** [bryanbartow/homebridge-alarm.com#34]
when I run Homebridge, it throws the following error for alarm.com.  

Jasons-iMac:~ jpstephens$ homebridge
[11/30/2016, 3:55:48 PM] Loaded plugin: homebridge-alarmdotcom
[11/30/2016, 3:55:48 PM] Registering platform 'homebridge-alarmdotcom.Alarmdotcom'
[11/30/2016, 3:55:48 PM] ---
[11/30/2016, 3:55:48 PM] Loaded plugin: homebridge-nest
[11/30/2016, 3:55:48 PM] Registering platform 'homebridge-nest.Nest'
[11/30/2016, 3:55:48 PM] ---
[11/30/2016, 3:55:48 PM] Loaded config.json with 0 accessories and 2 platforms.
[11/30/2016, 3:55:48 PM] ---
[11/30/2016, 3:55:48 PM] Loading 2 platforms...
[11/30/2016, 3:55:48 PM] Initializing Nest platform...
[11/30/2016, 3:55:48 PM] Fetching Nest devices.
[11/30/2016, 3:55:48 PM] [Security Panel] Initializing Alarmdotcom platform...
[11/30/2016, 3:55:50 PM] Software version for Living Room Thermostat is: 5.6-7
[11/30/2016, 3:55:50 PM] Temperature unit for Living Room Thermostat is: Fahrenheit
[11/30/2016, 3:55:50 PM] Current temperature for Living Room Thermostat is: 71 F
[11/30/2016, 3:55:50 PM] Current humidity for Living Room Thermostat is: 55%
[11/30/2016, 3:55:50 PM] Target temperature for Living Room Thermostat is: 70 F
[11/30/2016, 3:55:50 PM] Target heating for Living Room Thermostat is: Heating
[11/30/2016, 3:55:50 PM] Away for Living Room Thermostat is: 0
[11/30/2016, 3:55:50 PM] Initializing platform accessory 'Living Room Thermostat'...
[11/30/2016, 3:55:51 PM] [Security Panel] Error while getting light devices: TypeError: Cannot read property 'map' of undefined
[11/30/2016, 3:55:52 PM] [Security Panel] Error while getting lock devices: TypeError: Cannot read property 'map' of undefined
[11/30/2016, 3:55:52 PM] [Security Panel] Initializing platform accessory 'Alarm.com Security Panel'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:113:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:371:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Promise.all.then.results (/usr/local/lib/node_modules/homebridge-alarmdotcom/index.js:75:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)

When I load the Home App the security panel appears there.  How do I fix this error though?

**Comment by bryanbartow** [comment]
@jpstephens I haven't seen that error. Based solely on the error message, it looks maybe like you already have something else running on port 51826 or for some reason Homebridge thinks that. That's the port Homebridge uses by default. Maybe try editing the Homebridge config to run on another port and see if you get the same error?

**Comment by bryanbartow** [comment]
@jpstephens I just took a look over at the [Homebridge issues](https://github.com/nfarina/homebridge/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20Error%3A%20listen%20EADDRINUSE%20%3A%3A%3A51826) and it looks like others have had this issue for different reasons. Take a look and see if any of them apply to you. As far as I can tell, however, this is not an issue with this plugin and is an issue with your particular Homebridge setup. Therefore, I'm going to close the issue unless it can be determined that's not the case.

**Comment by jpstephens** [comment]
Bryan, 

I have set homebridge to launch automatically on startup of the computer in the background.  Could this be by I am getting this error when I try and launch it manually by typing “homebridge”?

**Comment by bryanbartow** [comment]
@jpstephens I'm sorry, but I can't help with Homebridge issues. You should probably post this on one of the issues I linked to in my previous reply.
