### ISSUE TITLE
Cannot read property 'panel' of undefined

### ISSUE THREAD

**Issue by ghost** [bryanbartow/homebridge-alarm.com#49]
Updated to latest this AM and am getting the below on startup:

[2/20/2017, 12:05:37 PM] [Security Panel] Initializing Alarmdotcom platform...
/usr/lib/node_modules/homebridge-alarmdotcom/index.js:71
                        if (this.config.accessories.panel === true) {
                                                   ^

TypeError: Cannot read property 'panel' of undefined
    at ADCPlatform.accessories (/usr/lib/node_modules/homebridge-alarmdotcom/index.js:71:31)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:351:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:295:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:77:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by davidvanvo** [comment]
@arontx what version were you prior? see readme for the latest config setting changes.

**Comment by ghost** [comment]
I see the config change and just updated accordingly but now I'm getting 

[2/20/2017, 12:14:44 PM] [Security Panel] Initializing Alarmdotcom platform...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by davidvanvo** [comment]
there was also a new WrapAPI, getviewstate that can be found in the Readme

**Comment by ghost** [comment]
Added, same error :(

**Comment by davidvanvo** [comment]
it appears your prior homebridge is still running off of the same address. i would confirm that you properly killed it or restart the machine.

**Comment by ghost** [comment]
Actually that might indicate homebridge is already running, my bad! Rebooting my pi to get a clean start

**Comment by ghost** [comment]
Damn dude you're awesome. Thank you!

**Comment by davidvanvo** [comment]
glad you figured it out.

@bryanbartow gets the credit. just here to assist.

**Comment by bryanbartow** [comment]
Nothing to see here, then? I'm closing.
