### ISSUE TITLE
homebridge module not getting past startup

### ISSUE THREAD

**Issue by FrancoJim** [bryanbartow/homebridge-alarm.com#52]
Getting error when starting homebridge. Looks to be an issue within the code. Possibly issue dependency?

> ==> launch.err.txt <==
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

>==> launch.out.txt <==
[2/24/2017, 11:05:04 PM] Loaded config.json with 0 accessories and 4 platforms.
[2/24/2017, 11:05:04 PM] ---
[2/24/2017, 11:05:04 PM] Loading 4 platforms...
[2/24/2017, 11:05:04 PM] [Homebridge Server] Initializing Server platform...
[2/24/2017, 11:05:04 PM] [Alarm] Initializing Alarmdotcom platform...

**Comment by bryanbartow** [comment]
@daklang That's a fairly vague statement. Perhaps you could run homebridge in debug mode and get some more verbose output? Also, are you sure you've followed the directions in the readme exactly? Most, but not all, issues seem to arise from misconfiguration or missing WrapAPI calls.

**Comment by bryanbartow** [comment]
@daklang Any update?

**Comment by danemacmillan** [comment]
Maybe he forgot to update his `config.json` file to include the new `accessories` object.

**Comment by jdshkolnik** [comment]
It's unlikely this is still a problem for the original poster.
