### ISSUE TITLE
Homebridge launches and fails after alarm attempt

### ISSUE THREAD

**Issue by rehafer** [bryanbartow/homebridge-alarm.com#7]
Everything appears to start start normally and then wen i try to access the Security Panel, Homebridge crashes and I get this:
[4/10/2016, 5:02:41 PM] [Security Panel] getting sessionUrl
/opt/local/lib/node_modules/homebridge-alarmdotcom/index.js:53
      this.sessionUrl = json.data.sessionUrl;
                                 ^

TypeError: Cannot read property 'sessionUrl' of undefined
    at AlarmcomAccessory.<anonymous> (/opt/local/lib/node_modules/homebridge-alarmdotcom/index.js:53:34)
    at Request.self.callback (/opt/local/lib/node_modules/homebridge-alarmdotcom/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/local/lib/node_modules/homebridge-alarmdotcom/node_modules/request/request.js:1041:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/opt/local/lib/node_modules/homebridge-alarmdotcom/node_modules/request/request.js:968:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

any ideas?

**Comment by bryanbartow** [comment]
@rehafer First, are you sure you're using the latest version (0.2.22)? Second, are you using a server API key from WrapAPI? There was some confusion about whether to use a server or client API key. I have since updated the documentation to specify.

**Comment by bryanbartow** [comment]
@rehafer Any update on this? I'd like to close this one way or the other.
